CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE "users" ("id" uuid DEFAULT uuid_generate_v4(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"username" text NOT NULL,"email" text NOT NULL,"password_hash" text NOT NULL,"is_active" boolean DEFAULT false,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_users_email" ON "users" ("email");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_users_username" ON "users" ("username");
CREATE INDEX IF NOT EXISTS "idx_users_deleted_at" ON "users" ("deleted_at");
CREATE TABLE "user_profiles" ("id" uuid DEFAULT uuid_generate_v4(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"user_id" uuid NOT NULL,"first_name" text,"last_name" text,"phone_number" text,"avatar_url" text,"bio" text,"date_of_birth" timestamptz,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_user_profiles_user_id" ON "user_profiles" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_user_profiles_deleted_at" ON "user_profiles" ("deleted_at");
CREATE TABLE "sessions" ("id" uuid DEFAULT uuid_generate_v4(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"user_id" uuid NOT NULL,"jwt_id" uuid NOT NULL,"refresh_token" text NOT NULL,"expires_at" timestamptz NOT NULL,"revoked" boolean DEFAULT false,"ip_address" text,"user_agent" text,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_sessions_jwt_id" ON "sessions" ("jwt_id");
CREATE INDEX IF NOT EXISTS "idx_sessions_user_id" ON "sessions" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_sessions_deleted_at" ON "sessions" ("deleted_at");
CREATE TABLE "roles" ("id" uuid DEFAULT uuid_generate_v4(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"name" text NOT NULL,"description" text,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_roles_name" ON "roles" ("name");
CREATE INDEX IF NOT EXISTS "idx_roles_deleted_at" ON "roles" ("deleted_at");
CREATE TABLE "permissions" ("id" uuid DEFAULT uuid_generate_v4(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"name" text NOT NULL,"description" text,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_permissions_name" ON "permissions" ("name");
CREATE INDEX IF NOT EXISTS "idx_permissions_deleted_at" ON "permissions" ("deleted_at");
CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL,"permission_id" uuid NOT NULL);
CREATE INDEX IF NOT EXISTS "idx_role_permissions_permission_id" ON "role_permissions" ("permission_id");
CREATE INDEX IF NOT EXISTS "idx_role_permissions_role_id" ON "role_permissions" ("role_id");
CREATE TABLE "user_roles" ("user_id" uuid NOT NULL,"role_id" uuid NOT NULL);
CREATE INDEX IF NOT EXISTS "idx_user_roles_role_id" ON "user_roles" ("role_id");
CREATE INDEX IF NOT EXISTS "idx_user_roles_user_id" ON "user_roles" ("user_id");
ALTER TABLE "user_profiles" ADD CONSTRAINT "fk_users_profile" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "role_permissions" ADD CONSTRAINT "fk_permissions_roles" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id");
ALTER TABLE "role_permissions" ADD CONSTRAINT "fk_roles_permissions" FOREIGN KEY ("role_id") REFERENCES "roles"("id");
ALTER TABLE "user_roles" ADD CONSTRAINT "fk_roles_users" FOREIGN KEY ("role_id") REFERENCES "roles"("id");
ALTER TABLE "user_roles" ADD CONSTRAINT "fk_users_roles" FOREIGN KEY ("user_id") REFERENCES "users"("id");
